#!/usr/bin/env bash

# Git shortcuts
alias git=hub
alias ga='git add -p'
alias gm='git merge'
alias gb='git branch'
alias gs='git status -sb'
alias gco='git checkout'
alias gc='git commit -m"$1"'
alias gg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %C(green)(%cr by %C(blue)%an)%Creset' --abbrev-commit"
alias gf='git fetch'

# pushing
alias gp='git push origin'
alias gpu='git push upstream'
alias gph='git push hub'
alias gpw='git push web'
alias gpd='git push dev'

# pulling
alias gl='git pull'
alias glu='git pull upstream'
alias glh='git pull hub'
alias glw='git pull web'
alias gmv='git mv'
function gcd {
    git add -u && git commit -am"$1" && git push dev
}
alias gd='git diff'
alias gdc='git diff --cached'
