#!/usr/bin/env bash

# Aliases
alias asdf='loadkeys /usr/share/kbd/keymaps/i386/dvorak/dvorak.map.gz'
#alias aoeu='loadkeys /usr/lib/kbd/keytables/us.map'
alias aoeu='loadkeys /usr/share/kbd/keymaps/i386/qwerty/us.map.gz'
alias fn='find -name'
function files {
  if [ -z "$1" ]; then
    find . -path ./.git -prune -o -print -path ./.hg -prune -o -print | wc -l
  else
    find $1 -type f | wc -l
  fi
}

# Django shortcuts
alias djt='python manage.py test'
alias djs='python manage.py runserver 0.0.0.0:11890'

alias cf='mallow'

# Directory Movements
alias pd='pushd'
alias Pd='popd'


export HISTIGNORE="fg*"
export HISTFILESIZE=99999

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=always'
    alias ack='ack --color'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lc='clear;ls'
alias c='clear'

alias ca='clear;ack'
alias a='ack'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# use ssh instead of su so that I can use public key login :)
alias 'sur'='ssh root@localhost'
